# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55b14d6b61399f78d0c4bdaf822a9a3f20c55fff20422e2c23d910cd2206bed60c6e13ca48eecd6fdf780cf3bb5ca47c04ad60f7ba2b6de5e9fdeff7ca2286b5

test:
  secret_key_base: f7fff46ca0184952f92ea6a281697cf8314980714bf57b3febe3647ec751b2e70306ef937113cd19a14d3537a72f922c00721b2aeb917be60279c58f47336858

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
